### PR TITLE
Refactor testcases

### PR DESCRIPTION
**Pull request by achew22**
Refactor the test cases into input/output files to make it simpler to add
and modify them.

Test cases can now be defined by creating a file inside
`testdata/default` (for the default test suite) or by creating a new
directory in `testdata`. This new directory should contain a set of
input files (`*.in.md`) and matching output files (`*.out.md`) as well
as a single `options.json` that defines the set of options to invoke the
markdown formatter with.

Additionally adds new flag to the test cases called "-update_goldens"
that writes the matching `.out.md` file if the testcase fails.

### CODE REVIEW

**Comment by achew22** [comment]
With https://github.com/russross/blackfriday/pull/521 I think the regression in blackfriday is not long for this world. I'm happy to wait until then to update and then merge.

**Comment by achew22** [comment]
Now that https://github.com/russross/blackfriday/issues/495 is fixed, I have updated the test cases to reflect the correct behavior. @dmitshur, do you think it is now reasonable to merge this?

PS: it was a joy to update the tests after the blackfriday update `go get -u ./... && go test ./... -update_goldens && go test ./... && git commit --amend && git push -f`

**Comment by achew22** [comment]
@dmitshur, friendly ping

**Comment by achew22** [comment]
@dmitshur, friendly ping

**Comment by dmitshur** [comment]
Hi @achew22, thanks for the pings, they are helpful.

This is on my radar, but I have some more pressing and time-sensitive work to complete first. I hope I'll be able to get to this next weekend or so.

Sorry about the delay in getting to this, I haven't had many resources available for open source maintenance lately.

**Comment by achew22** [comment]
@dmitshur, thanks so much for replying! Is there anything I can do to lighten that load? I'm also a [Googler](http://go/achew) so if you wanted to move this from your personal account under the `google` github user and then share the labor I would be more than happy to help.

**Comment by dmitshur** [comment]
Thanks for the offer to help! I will need to think more about this, and will get back to you, just after this week. :)

**Comment by achew22** [comment]
Friendliest of pings

**Pull request merged**
